#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrtInsManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db.demo")]
	public partial class dbINSManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InserttCustomerPolicy(tCustomerPolicy instance);
    partial void UpdatetCustomerPolicy(tCustomerPolicy instance);
    partial void DeletetCustomerPolicy(tCustomerPolicy instance);
    partial void InserttCustomerINS(tCustomerINS instance);
    partial void UpdatetCustomerINS(tCustomerINS instance);
    partial void DeletetCustomerINS(tCustomerINS instance);
    partial void InserttAgent(tAgent instance);
    partial void UpdatetAgent(tAgent instance);
    partial void DeletetAgent(tAgent instance);
    #endregion
		
		public dbINSManagementDataContext() : 
				base(global::PrtInsManagement.Properties.Settings.Default.db_demoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbINSManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbINSManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbINSManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbINSManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tCustomerPolicy> tCustomerPolicy
		{
			get
			{
				return this.GetTable<tCustomerPolicy>();
			}
		}
		
		public System.Data.Linq.Table<tCustomerINS> tCustomerINS
		{
			get
			{
				return this.GetTable<tCustomerINS>();
			}
		}
		
		public System.Data.Linq.Table<tAgent> tAgent
		{
			get
			{
				return this.GetTable<tAgent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tCustomerPolicy")]
	public partial class tCustomerPolicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fCustomerPolicyID;
		
		private string _fCustomerID;
		
		private string _fFirstName;
		
		private string _fLastName;
		
		private string _fPolicyType;
		
		private System.DateTime _fPeriod_StartDate;
		
		private string _fPolicy_FiscalPeriod;
		
		private string _fAgentID;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfCustomerPolicyIDChanging(int value);
    partial void OnfCustomerPolicyIDChanged();
    partial void OnfCustomerIDChanging(string value);
    partial void OnfCustomerIDChanged();
    partial void OnfFirstNameChanging(string value);
    partial void OnfFirstNameChanged();
    partial void OnfLastNameChanging(string value);
    partial void OnfLastNameChanged();
    partial void OnfPolicyTypeChanging(string value);
    partial void OnfPolicyTypeChanged();
    partial void OnfPeriod_StartDateChanging(System.DateTime value);
    partial void OnfPeriod_StartDateChanged();
    partial void OnfPolicy_FiscalPeriodChanging(string value);
    partial void OnfPolicy_FiscalPeriodChanged();
    partial void OnfAgentIDChanging(string value);
    partial void OnfAgentIDChanged();
    #endregion
		
		public tCustomerPolicy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCustomerPolicyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fCustomerPolicyID
		{
			get
			{
				return this._fCustomerPolicyID;
			}
			set
			{
				if ((this._fCustomerPolicyID != value))
				{
					this.OnfCustomerPolicyIDChanging(value);
					this.SendPropertyChanging();
					this._fCustomerPolicyID = value;
					this.SendPropertyChanged("fCustomerPolicyID");
					this.OnfCustomerPolicyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCustomerID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fCustomerID
		{
			get
			{
				return this._fCustomerID;
			}
			set
			{
				if ((this._fCustomerID != value))
				{
					this.OnfCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._fCustomerID = value;
					this.SendPropertyChanged("fCustomerID");
					this.OnfCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fFirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fFirstName
		{
			get
			{
				return this._fFirstName;
			}
			set
			{
				if ((this._fFirstName != value))
				{
					this.OnfFirstNameChanging(value);
					this.SendPropertyChanging();
					this._fFirstName = value;
					this.SendPropertyChanged("fFirstName");
					this.OnfFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fLastName
		{
			get
			{
				return this._fLastName;
			}
			set
			{
				if ((this._fLastName != value))
				{
					this.OnfLastNameChanging(value);
					this.SendPropertyChanging();
					this._fLastName = value;
					this.SendPropertyChanged("fLastName");
					this.OnfLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPolicyType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fPolicyType
		{
			get
			{
				return this._fPolicyType;
			}
			set
			{
				if ((this._fPolicyType != value))
				{
					this.OnfPolicyTypeChanging(value);
					this.SendPropertyChanging();
					this._fPolicyType = value;
					this.SendPropertyChanged("fPolicyType");
					this.OnfPolicyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPeriod_StartDate", DbType="Date NOT NULL")]
		public System.DateTime fPeriod_StartDate
		{
			get
			{
				return this._fPeriod_StartDate;
			}
			set
			{
				if ((this._fPeriod_StartDate != value))
				{
					this.OnfPeriod_StartDateChanging(value);
					this.SendPropertyChanging();
					this._fPeriod_StartDate = value;
					this.SendPropertyChanged("fPeriod_StartDate");
					this.OnfPeriod_StartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPolicy_FiscalPeriod", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fPolicy_FiscalPeriod
		{
			get
			{
				return this._fPolicy_FiscalPeriod;
			}
			set
			{
				if ((this._fPolicy_FiscalPeriod != value))
				{
					this.OnfPolicy_FiscalPeriodChanging(value);
					this.SendPropertyChanging();
					this._fPolicy_FiscalPeriod = value;
					this.SendPropertyChanged("fPolicy_FiscalPeriod");
					this.OnfPolicy_FiscalPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAgentID", DbType="NChar(10)")]
		public string fAgentID
		{
			get
			{
				return this._fAgentID;
			}
			set
			{
				if ((this._fAgentID != value))
				{
					this.OnfAgentIDChanging(value);
					this.SendPropertyChanging();
					this._fAgentID = value;
					this.SendPropertyChanged("fAgentID");
					this.OnfAgentIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tCustomerINS")]
	public partial class tCustomerINS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fCustomerID;
		
		private string _fFirstName;
		
		private string _fLastName;
		
		private System.DateTime _fDOB;
		
		private string _fAge;
		
		private string _fGender;
		
		private string _fState;
		
		private string _fCity;
		
		private string _fAddress;
		
		private string _fZipcode;
		
		private string _fContactPhone;
		
		private string _fOccupation;
		
		private string _fDegree;
		
		private string _fDriverLicense;
		
		private string _fAgentName;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfCustomerIDChanging(int value);
    partial void OnfCustomerIDChanged();
    partial void OnfFirstNameChanging(string value);
    partial void OnfFirstNameChanged();
    partial void OnfLastNameChanging(string value);
    partial void OnfLastNameChanged();
    partial void OnfDOBChanging(System.DateTime value);
    partial void OnfDOBChanged();
    partial void OnfAgeChanging(string value);
    partial void OnfAgeChanged();
    partial void OnfGenderChanging(string value);
    partial void OnfGenderChanged();
    partial void OnfStateChanging(string value);
    partial void OnfStateChanged();
    partial void OnfCityChanging(string value);
    partial void OnfCityChanged();
    partial void OnfAddressChanging(string value);
    partial void OnfAddressChanged();
    partial void OnfZipcodeChanging(string value);
    partial void OnfZipcodeChanged();
    partial void OnfContactPhoneChanging(string value);
    partial void OnfContactPhoneChanged();
    partial void OnfOccupationChanging(string value);
    partial void OnfOccupationChanged();
    partial void OnfDegreeChanging(string value);
    partial void OnfDegreeChanged();
    partial void OnfDriverLicenseChanging(string value);
    partial void OnfDriverLicenseChanged();
    partial void OnfAgentNameChanging(string value);
    partial void OnfAgentNameChanged();
    #endregion
		
		public tCustomerINS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCustomerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fCustomerID
		{
			get
			{
				return this._fCustomerID;
			}
			set
			{
				if ((this._fCustomerID != value))
				{
					this.OnfCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._fCustomerID = value;
					this.SendPropertyChanged("fCustomerID");
					this.OnfCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fFirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fFirstName
		{
			get
			{
				return this._fFirstName;
			}
			set
			{
				if ((this._fFirstName != value))
				{
					this.OnfFirstNameChanging(value);
					this.SendPropertyChanging();
					this._fFirstName = value;
					this.SendPropertyChanged("fFirstName");
					this.OnfFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fLastName
		{
			get
			{
				return this._fLastName;
			}
			set
			{
				if ((this._fLastName != value))
				{
					this.OnfLastNameChanging(value);
					this.SendPropertyChanging();
					this._fLastName = value;
					this.SendPropertyChanged("fLastName");
					this.OnfLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDOB", DbType="Date NOT NULL")]
		public System.DateTime fDOB
		{
			get
			{
				return this._fDOB;
			}
			set
			{
				if ((this._fDOB != value))
				{
					this.OnfDOBChanging(value);
					this.SendPropertyChanging();
					this._fDOB = value;
					this.SendPropertyChanged("fDOB");
					this.OnfDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAge", DbType="NChar(10)")]
		public string fAge
		{
			get
			{
				return this._fAge;
			}
			set
			{
				if ((this._fAge != value))
				{
					this.OnfAgeChanging(value);
					this.SendPropertyChanging();
					this._fAge = value;
					this.SendPropertyChanged("fAge");
					this.OnfAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fGender
		{
			get
			{
				return this._fGender;
			}
			set
			{
				if ((this._fGender != value))
				{
					this.OnfGenderChanging(value);
					this.SendPropertyChanging();
					this._fGender = value;
					this.SendPropertyChanged("fGender");
					this.OnfGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fState", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fState
		{
			get
			{
				return this._fState;
			}
			set
			{
				if ((this._fState != value))
				{
					this.OnfStateChanging(value);
					this.SendPropertyChanging();
					this._fState = value;
					this.SendPropertyChanged("fState");
					this.OnfStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fCity
		{
			get
			{
				return this._fCity;
			}
			set
			{
				if ((this._fCity != value))
				{
					this.OnfCityChanging(value);
					this.SendPropertyChanging();
					this._fCity = value;
					this.SendPropertyChanged("fCity");
					this.OnfCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAddress
		{
			get
			{
				return this._fAddress;
			}
			set
			{
				if ((this._fAddress != value))
				{
					this.OnfAddressChanging(value);
					this.SendPropertyChanging();
					this._fAddress = value;
					this.SendPropertyChanged("fAddress");
					this.OnfAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fZipcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fZipcode
		{
			get
			{
				return this._fZipcode;
			}
			set
			{
				if ((this._fZipcode != value))
				{
					this.OnfZipcodeChanging(value);
					this.SendPropertyChanging();
					this._fZipcode = value;
					this.SendPropertyChanged("fZipcode");
					this.OnfZipcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fContactPhone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fContactPhone
		{
			get
			{
				return this._fContactPhone;
			}
			set
			{
				if ((this._fContactPhone != value))
				{
					this.OnfContactPhoneChanging(value);
					this.SendPropertyChanging();
					this._fContactPhone = value;
					this.SendPropertyChanged("fContactPhone");
					this.OnfContactPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOccupation", DbType="NVarChar(50)")]
		public string fOccupation
		{
			get
			{
				return this._fOccupation;
			}
			set
			{
				if ((this._fOccupation != value))
				{
					this.OnfOccupationChanging(value);
					this.SendPropertyChanging();
					this._fOccupation = value;
					this.SendPropertyChanged("fOccupation");
					this.OnfOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDegree", DbType="NVarChar(50)")]
		public string fDegree
		{
			get
			{
				return this._fDegree;
			}
			set
			{
				if ((this._fDegree != value))
				{
					this.OnfDegreeChanging(value);
					this.SendPropertyChanging();
					this._fDegree = value;
					this.SendPropertyChanged("fDegree");
					this.OnfDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDriverLicense", DbType="NVarChar(50)")]
		public string fDriverLicense
		{
			get
			{
				return this._fDriverLicense;
			}
			set
			{
				if ((this._fDriverLicense != value))
				{
					this.OnfDriverLicenseChanging(value);
					this.SendPropertyChanging();
					this._fDriverLicense = value;
					this.SendPropertyChanged("fDriverLicense");
					this.OnfDriverLicenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAgentName", DbType="NVarChar(50)")]
		public string fAgentName
		{
			get
			{
				return this._fAgentName;
			}
			set
			{
				if ((this._fAgentName != value))
				{
					this.OnfAgentNameChanging(value);
					this.SendPropertyChanging();
					this._fAgentName = value;
					this.SendPropertyChanged("fAgentName");
					this.OnfAgentNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tAgent")]
	public partial class tAgent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fAgentID;
		
		private string _fFirstName;
		
		private string _fLastName;
		
		private string _fAge;
		
		private string _fGender;
		
		private string _fOccupation;
		
		private string _fContact;
		
		private string _fAgentEmail;
		
		private string _fPassword;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfAgentIDChanging(int value);
    partial void OnfAgentIDChanged();
    partial void OnfFirstNameChanging(string value);
    partial void OnfFirstNameChanged();
    partial void OnfLastNameChanging(string value);
    partial void OnfLastNameChanged();
    partial void OnfAgeChanging(string value);
    partial void OnfAgeChanged();
    partial void OnfGenderChanging(string value);
    partial void OnfGenderChanged();
    partial void OnfOccupationChanging(string value);
    partial void OnfOccupationChanged();
    partial void OnfContactChanging(string value);
    partial void OnfContactChanged();
    partial void OnfAgentEmailChanging(string value);
    partial void OnfAgentEmailChanged();
    partial void OnfPasswordChanging(string value);
    partial void OnfPasswordChanged();
    #endregion
		
		public tAgent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAgentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fAgentID
		{
			get
			{
				return this._fAgentID;
			}
			set
			{
				if ((this._fAgentID != value))
				{
					this.OnfAgentIDChanging(value);
					this.SendPropertyChanging();
					this._fAgentID = value;
					this.SendPropertyChanged("fAgentID");
					this.OnfAgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fFirstName", DbType="NVarChar(50)")]
		public string fFirstName
		{
			get
			{
				return this._fFirstName;
			}
			set
			{
				if ((this._fFirstName != value))
				{
					this.OnfFirstNameChanging(value);
					this.SendPropertyChanging();
					this._fFirstName = value;
					this.SendPropertyChanged("fFirstName");
					this.OnfFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLastName", DbType="NVarChar(50)")]
		public string fLastName
		{
			get
			{
				return this._fLastName;
			}
			set
			{
				if ((this._fLastName != value))
				{
					this.OnfLastNameChanging(value);
					this.SendPropertyChanging();
					this._fLastName = value;
					this.SendPropertyChanged("fLastName");
					this.OnfLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAge", DbType="NVarChar(50)")]
		public string fAge
		{
			get
			{
				return this._fAge;
			}
			set
			{
				if ((this._fAge != value))
				{
					this.OnfAgeChanging(value);
					this.SendPropertyChanging();
					this._fAge = value;
					this.SendPropertyChanged("fAge");
					this.OnfAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fGender", DbType="NVarChar(50)")]
		public string fGender
		{
			get
			{
				return this._fGender;
			}
			set
			{
				if ((this._fGender != value))
				{
					this.OnfGenderChanging(value);
					this.SendPropertyChanging();
					this._fGender = value;
					this.SendPropertyChanged("fGender");
					this.OnfGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fOccupation", DbType="NVarChar(50)")]
		public string fOccupation
		{
			get
			{
				return this._fOccupation;
			}
			set
			{
				if ((this._fOccupation != value))
				{
					this.OnfOccupationChanging(value);
					this.SendPropertyChanging();
					this._fOccupation = value;
					this.SendPropertyChanged("fOccupation");
					this.OnfOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fContact", DbType="NVarChar(50)")]
		public string fContact
		{
			get
			{
				return this._fContact;
			}
			set
			{
				if ((this._fContact != value))
				{
					this.OnfContactChanging(value);
					this.SendPropertyChanging();
					this._fContact = value;
					this.SendPropertyChanged("fContact");
					this.OnfContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAgentEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAgentEmail
		{
			get
			{
				return this._fAgentEmail;
			}
			set
			{
				if ((this._fAgentEmail != value))
				{
					this.OnfAgentEmailChanging(value);
					this.SendPropertyChanging();
					this._fAgentEmail = value;
					this.SendPropertyChanged("fAgentEmail");
					this.OnfAgentEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fPassword
		{
			get
			{
				return this._fPassword;
			}
			set
			{
				if ((this._fPassword != value))
				{
					this.OnfPasswordChanging(value);
					this.SendPropertyChanging();
					this._fPassword = value;
					this.SendPropertyChanged("fPassword");
					this.OnfPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
